INSERT INTO songs
    (song_name, album)
    VALUES 
        ('Bad Boy', 1),
        ('All Right', 1),
        ('Peek-A-Boo', 1),
        ('Look', 1),
        ('I Just', 1),
        ('Kingdom Come', 1),
        ('Time To Love', 1),
        ('My Second Date', 1),
        ('Attaboy', 1),
        ('Perfect 10', 1),
        ('About Love', 1),
        ('Moonlight Melody', 1),
        ('Russian Roulette', 2),
        ('Lucky Girl', 2),
        ('Bad Dracula', 2),
        ('Sunny Afternoon', 2),
        ('Fool', 2),
        ('Some Love', 2),
        ('My Dear', 2),
        ('Psycho', 3),
        ('In & Out', 3),
        ('Remember Forever', 3),
        ('Eyes Locked, Hands Locked', 3),
        ('Ladies Night', 3),
        ('Jumpin''', 3),
        ('Love Is The Way', 3),
        ('Carpool', 3),
        ('Umpah Umpah', 3),
        ('LP', 3),
        ('Parade', 3),
        ('Bing Bing', 3),
        ('Milkshake', 3),
        ('Sunny Side Up!', 3),
        ('Zimzalabim', 3),
        ('La Rouge', 3),
        ('Highway to Heaven', 4),
        ('Superhuman', 4),
        ('FOOL', 4),
        ('Jet Lag', 4),
        ('Paper Plane', 4),
        ('Outro: WE ARE 127', 4),
        ('Elevator (127F)', 5),
        ('Kick It', 5),
        ('Boom', 5),
        ('Pandora''s Box', 5),
        ('Day Dream', 5),
        ('Interlude: Neo Zone', 5),
        ('MAD DOG', 5),
        ('Sit Down!', 5),
        ('Love Me Now', 5),
        ('Love Song', 5),
        ('White Night', 5),
        ('Not Alone', 5),
        ('Dreams Come True', 5),
        ('Wild', 6),
        ('Bite', 6),
        ('Fools', 6),
        ('Ease (ft Broods)', 6),
        ('The Quiet', 6),
        ('DKLA (ft Tkay Maidza', 6),
        ('Talk Me Down', 6),
        ('Cool', 6),
        ('Heaven (ft Betty Who', 6),
        ('Youth', 6),
        ('Lost Boy', 6),
        ('for him. (ft Allday)', 6),
        ('Suburbia', 6),
        ('Blue (ft Alex Hope)', 6),
        ('Wild (XXYYXX Remix)', 6),
        ('Take Yourself Home', 7),
        ('Easy', 7),
        ('could cry just thinkin about you', 7),
        ('STUD', 7),
        ('Rager Teenager!', 7),
        ('IN A DREAM', 7),
        ('Honeymoon Avenue', 8),
        ('Baby I', 8),
        ('Right There (ft Big Sean)', 8),
        ('Tattooed Heart', 8),
        ('Lovin'' It', 8),
        ('Piano', 8),
        ('Daydreamin''', 8),
        ('The Way (ft Mac Miller)', 8),
        ('You''ll Never Know', 8),
        ('Almost is Never Enough (ft Nathan Sykes)', 8),
        ('Popular Song (ft Mika)', 8),
        ('Better Left Unsaid', 8),
        ('Moonlight', 9),
        ('Dangerous Woman', 9),
        ('Be Alright', 9),
        ('Into You', 9),
        ('Side To Side (ft Nicki Minaj)', 9),
        ('Let Me Love You (ft Lil Wayne)', 9),
        ('Greedy', 9),
        ('Leave Me Lonely (ft Macy Gray)', 9),
        ('Everyday (ft Future)', 9),
        ('Sometimes', 9),
        ('I Don''t Care', 9),
        ('Bad Decisions', 9),
        ('Touch It', 9),
        ('Knew Better / Forever Boy', 9),
        ('Thinking Bout You', 9),
        ('How You Like That', 10),
        ('Ice Cream', 10),
        ('Pretty Savage', 10),
        ('Bet You Wanna', 10),
        ('Lovesick Girls', 10),
        ('Crazy Over You', 10),
        ('Love To Hate Me', 10),
        ('You Never Know', 10),
        ('DDU-DU DDU-DU', 11),
        ('Forever Young', 11),
        ('Really', 11),
        ('See U Later', 11),
        ('As If It''s Your Last', 11),
        ('Comfort Crowd', 12),
        ('Wish You Were Sober', 12),
        ('Maniac', 12),
        ('(Online Love)', 12),
        ('Checkmate', 12),
        ('The Cut That Always Bleeds', 12),
        ('Fight or Flight', 12),
        ('Affluenza', 12),
        ('(Can We Be Friends?)', 12),
        ('Heather', 12),
        ('Little League', 12),
        ('The Story', 12),
        ('To Be One (Intro.)', 13),
        ('Burn It Up', 13),
        ('Energetic', 13),
        ('Wanna Be (My Baby)', 13),
        ('Always (Acoustic Ver.)', 13),
        ('Pick Me', 13),
        ('Never', 13),
        ('Gold', 14),
        ('I Promise You (I.P.U.)', 14),
        ('Boomerang', 14),
        ('We Are', 14),
        ('Day By Day', 14),
        ('I''ll Remember', 14),
        ('I Promise You (Propose Ver.)', 14),
        ('imagine', 15),
        ('needy', 15),
        ('NASA', 15),
        ('bloodline', 15),
        ('fake smile', 15),
        ('bad idea', 15),
        ('make up', 15),
        ('ghostin', 15),
        ('in my head', 15),
        ('7 rings', 15),
        ('thank u, next', 15),
        ('break up with your girlfriend, i''m bored', 15),
        ('Birthday', 16),
        ('Slow Down', 16),
        ('Stars Dance', 16),
        ('Like a Champion', 16),
        ('Come & Get It', 16),
        ('Forget Forever', 16),
        ('Save the Day', 16),
        ('B.E.A.T.', 16),
        ('Write Your Name', 16),
        ('Undercover', 16),
        ('Love Will Remember', 16);